// src/pages/Home.jsx
import React from "react";
import { Link } from "react-router-dom";
import { FiEdit, FiFileText, FiDownload } from "react-icons/fi";

const Home = () => {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 text-white py-28 px-6 text-center relative overflow-hidden">
        <h1 className="text-5xl md:text-6xl font-extrabold mb-4 animate-fadeIn">
          AI Script Writer
        </h1>
        <p className="text-lg md:text-xl mb-10 animate-fadeIn delay-200">
          Generate full scripts from your story ideas or explore AI-generated stories in seconds!
        </p>
        <div className="flex justify-center gap-6 animate-fadeIn delay-400">
          <Link
            to="/register"
            className="bg-white text-indigo-600 font-semibold py-3 px-8 rounded-full shadow-lg hover:bg-gray-100 transition-all duration-300"
          >
            Get Started
          </Link>
          <Link
            to="/login"
            className="bg-transparent border-2 border-white py-3 px-8 rounded-full hover:bg-white hover:text-indigo-600 transition-all duration-300"
          >
            Login
          </Link>
        </div>
        {/* Decorative Circles */}
        <div className="absolute top-0 left-0 w-72 h-72 bg-pink-400 opacity-20 rounded-full -translate-x-1/2 -translate-y-1/2 animate-pulse-slow"></div>
        <div className="absolute bottom-0 right-0 w-72 h-72 bg-yellow-300 opacity-20 rounded-full translate-x-1/2 translate-y-1/2 animate-pulse-slow"></div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6 bg-gray-50 text-gray-800">
        <h2 className="text-3xl md:text-4xl font-bold text-center mb-14">
          Why Choose Us?
        </h2>
        <div className="grid md:grid-cols-3 gap-10 max-w-6xl mx-auto">
          <div className="bg-white shadow-lg p-8 rounded-xl hover:shadow-2xl transition-all duration-300 text-center">
            <div className="text-indigo-600 text-4xl mb-4 inline-block">
              <FiEdit />
            </div>
            <h3 className="text-xl font-semibold mb-3">Personal Story Scripts</h3>
            <p>Turn your own story ideas into full-length scripts effortlessly with AI guidance.</p>
          </div>
          <div className="bg-white shadow-lg p-8 rounded-xl hover:shadow-2xl transition-all duration-300 text-center">
            <div className="text-indigo-600 text-4xl mb-4 inline-block">
              <FiFileText />
            </div>
            <h3 className="text-xl font-semibold mb-3">AI Generated Stories</h3>
            <p>Explore pre-built story ideas generated by our AI, ready for customization and expansion.</p>
          </div>
          <div className="bg-white shadow-lg p-8 rounded-xl hover:shadow-2xl transition-all duration-300 text-center">
            <div className="text-indigo-600 text-4xl mb-4 inline-block">
              <FiDownload />
            </div>
            <h3 className="text-xl font-semibold mb-3">Download & Share</h3>
            <p>Export your scripts in PDF, TXT, or DOCX formats to share with collaborators or producers.</p>
          </div>
        </div>
      </section>

      {/* Subscription Section */}
      <section className="py-20 px-6 bg-gradient-to-r from-purple-600 to-indigo-600 text-white text-center">
        <h2 className="text-3xl md:text-4xl font-bold mb-4">Start Free or Upgrade to Pro</h2>
        <p className="mb-10 max-w-2xl mx-auto">
          Free users get 5 scripts per month. Upgrade to Pro to unlock unlimited script generation and advanced features!
        </p>
        <div className="flex justify-center gap-6">
          <Link
            to="/register"
            className="bg-white text-purple-600 font-semibold py-3 px-8 rounded-full shadow-lg hover:bg-gray-100 transition-all duration-300"
          >
            Start Free
          </Link>
          <Link
            to="/pricing"
            className="bg-transparent border-2 border-white py-3 px-8 rounded-full hover:bg-white hover:text-purple-600 transition-all duration-300"
          >
            View Plans
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-6 text-center">
        <p>
          &copy; {new Date().getFullYear()} AI Script Writer. All rights reserved.
        </p>
      </footer>
    </div>
  );
};

export default Home;
